### ISSUE TITLE
add Laravel

### ISSUE THREAD

**Issue by andela-bkagia** [andela/resly#1]
We need to add Laravel as part of our ["Developer Workflow setup"](https://www.pivotaltracker.com/story/show/103165338) story

**Comment by andela-anandaa** [comment]
I'm wondering wether we should use Github Issue tracking or Pivotal Tracker, though I find Github has better userbility in terms of discussions, etc. I'll pick @andela-gukpere's brain on this one...

**Comment by kagia** [comment]
I prefer github's simplicity and UI.
