### ISSUE TITLE
The login and registration forms are not user-friendly at all as they fill the width of the entire page.

### ISSUE THREAD

**Issue by sirolad** [andela/resly#142]
![screen shot 2016-01-27 at 3 13 17 pm](https://cloud.githubusercontent.com/assets/13223767/12615939/de28e892-c508-11e5-9a63-8c18f229a3ef.png)

**Comment by sslgeorge** [comment]
The login page has been redesigned, its pull request has not been merged, the registration page will be handled soon. Thank you for your feedback.

**Comment by sslgeorge** [comment]
Thanks for your feedback, the issue has been taken care of.
